#server:
#  port: 88
#spring:
#  application:
#    name: mi-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: gitdlq.top:8848  #配置nacos地址
#    gateway:
#      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
#        - id: product_route
#          uri: lb://mi-product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
#        - id: member_route
#          uri: lb://mi-member
#          predicates:
#            - Path=/api/member/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
#        - id: order_route
#          uri: lb://mi-order
#          predicates:
#            - Path=/api/order/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
#        - id: ware_route
#          uri: lb://mi-ware
#          predicates:
#            - Path=/api/ware/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
#        - id: coupon_route
#          uri: lb://mi-coupon
#          predicates:
#            - Path=/api/coupon/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
#        - id: search_route
#          uri: lb://mi-search
#          predicates:
#            - Path=/api/search/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
#          #http://localhost:88/api/thirdparty/oss/policy
#        - id: third_party_route
#          uri: lb://mi-third-party
#          predicates:
#            - Path=/api/thirdparty/**
#          filters:
#            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}
#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
#        - id: jdmall_host_route
#          uri: lb://mi-product
#          predicates:
#            - Host=gitdlq.top
#        - id: jdmall_search_route
#          uri: lb://mi-search
#          predicates:
#            - Host=search.gitdlq.top
#        - id: jdmall_auth_route
#          uri: lb://mi-auth
#          predicates:
#            - Host=auth.gitdlq.top
