kind: Deployment
apiVersion: apps/v1
metadata:
  name: mi-third-party
  namespace: jdmall
  labels:
    app: mi-third-party
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/alias-name: sentinel
    kubesphere.io/maxSurgePod: '2'
    kubesphere.io/minAvailablePod: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-third-party
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mi-third-party
    spec:
      containers:
        - name: mi-third-party
          image: $REGISTRY/$HARBOR_NAMESPACE/$PROJECT_NAME:$PROJECT_VERSION
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 150Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: mi-third-party
  namespace: jdmall
  labels:
    app: mi-third-party
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: mi-third-party
  type: NodePort
  sessionAffinity: None

