#server:
#  port: 30000
#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848  #配置nacos地址
#spring:
#  cloud:
#    alicloud:
#      access-key: L
#      secret-key: j
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#        bucket: dlq-mi-mall
