#server:
#  port: 30000
#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848  #配置nacos地址
#spring:
#  cloud:
#    alicloud:
#      access-key: L
#      secret-key: j
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#        bucket: dlq-mi-mall
##阿里云短信
#aliyun:
#  sms:
#    regionId: cn-hangzhou
#    keyId: LTAI4
#    keySecret: ri4WsWdY3RL
#    templateCode: SMS_18
#    signName: JAV
