server:
  port: 11000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/mi_wms
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mi-ware
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
